# ===================================
# Spring Boot Configuration
# ===================================
spring.application.name=monitoring-service
server.port=8080

# ===================================
# JPA y Hibernate
# ===================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===================================
# H2 Database (En Memoria)
# ===================================
spring.datasource.url=jdbc:h2:mem:vehicledb
spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (solo para desarrollo)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===================================
# Logging
# ===================================
logging.level.root=INFO
logging.level.com.fleetguard=DEBUG
logging.level.org.springframework.web=INFO

# ===================================
# OpenAPI/Swagger
# ===================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
